# Generated by Django 5.2.3 on 2025-10-21 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lector',
            name='digito_verificador',
        ),
        migrations.AddField(
            model_name='lector',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lector',
            name='rut',
            field=models.CharField(help_text='Formato: 12.345.678-9', max_length=12, unique=True),
        ),
    ]
